# Generated by Django 4.2.17 on 2026-05-30 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='black_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='max_spectators',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='room',
            name='white_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SpectatorSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectators', to='game.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectator_seats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seat_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='spectatorseat',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_room_spectator_user'),
        ),
        migrations.AddConstraint(
            model_name='spectatorseat',
            constraint=models.UniqueConstraint(fields=('room', 'seat_number'), name='unique_room_spectator_seat'),
        ),
    ]
