# Generated by Django 4.2.17 on 2026-05-30 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_room_black_ready_room_last_activity_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=80)),
                ('rule_set', models.CharField(choices=[('standard', '无禁手'), ('renju', '有禁手')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('playing', '进行中'), ('finished', '已结束')], default='playing', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=10)),
                ('end_reason', models.CharField(blank=True, max_length=40)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('black_undo_used', models.PositiveSmallIntegerField(default=0)),
                ('white_undo_used', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='move',
            name='unique_room_move_number',
        ),
        migrations.RemoveConstraint(
            model_name='move',
            name='unique_room_point',
        ),
        migrations.AddField(
            model_name='room',
            name='black_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='white_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='black_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='game.room'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='white_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.gamesession'),
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.UniqueConstraint(fields=('game', 'move_number'), name='unique_game_move_number'),
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.UniqueConstraint(fields=('game', 'x', 'y'), name='unique_game_point'),
        ),
        migrations.AddField(
            model_name='room',
            name='current_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_room', to='game.gamesession'),
        ),
    ]
