# Generated by Django 4.2.17 on 2026-05-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_remove_move_unique_room_move_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='black_time_left_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='move_time_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='total_time_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='turn_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='white_time_left_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='room',
            name='move_time_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='room',
            name='total_time_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
    ]
