# Generated by Django 4.2.17 on 2026-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamesession_black_time_left_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pending_seat_switch_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='pending_undo_request',
            field=models.TextField(blank=True),
        ),
    ]
