# Generated by Django 4.2.17 on 2026-05-30 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_room_pending_seat_switch_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='game.room'),
        ),
    ]
