# Generated by Django 4.2.17 on 2026-05-30 16:29

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_admin(apps, _schema_editor):
    User = apps.get_model("auth", "User")
    PlayerProfile = apps.get_model("game", "PlayerProfile")
    admin, created = User.objects.get_or_create(username="admin")
    admin.is_staff = True
    admin.is_superuser = True
    admin.is_active = True
    admin.password = make_password("admin123321")
    admin.save()
    for user in User.objects.all():
        PlayerProfile.objects.get_or_create(user=user)


def noop(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_playerprofile'),
    ]

    operations = [
        migrations.RunPython(seed_admin, noop),
    ]
