# Generated by Django 4.2.17 on 2026-05-30 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0009_seed_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenMatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_for_users', to='game.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_match_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hidden_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='hiddenmatchrecord',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_hidden_match_per_user'),
        ),
    ]
