# Generated by Django 4.2.17 on 2026-05-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_hiddenmatchrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='move_time_seconds',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='room',
            name='move_time_seconds',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
