from django.urls import path

from . import views

urlpatterns = [
    path("auth/register/", views.register),
    path("auth/login/", views.login),
    path("auth/logout/", views.logout),
    path("auth/me/", views.me),
    path("profile/", views.update_profile),
    path("profile/password/", views.change_password),
    path("profile/matches/", views.match_history),
    path("profile/matches/<int:match_id>/", views.match_detail),
    path("admin/users/", views.admin_users),
    path("admin/users/<int:user_id>/", views.admin_user_detail),
    path("admin/rooms/", views.admin_rooms),
    path("admin/rooms/<int:room_id>/", views.admin_room_detail),
    path("users/<int:user_id>/", views.player_detail),
    path("leaderboard/", views.leaderboard),
    path("invitations/", views.pending_invitations),
    path("invitations/<int:invitation_id>/respond/", views.respond_invitation_view),
    path("online/", views.online_users),
    path("rooms/", views.rooms),
    path("rooms/count/", views.room_count),
    path("rooms/<int:room_id>/join/", views.join_room_view),
    path("rooms/<int:room_id>/settings/", views.room_settings_view),
    path("rooms/<int:room_id>/leave/", views.leave_room_view),
    path("rooms/<int:room_id>/kick/", views.kick_room_user_view),
    path("rooms/<int:room_id>/invite/", views.invite_room_user_view),
    path("rooms/<int:room_id>/state/", views.room_state),
    path("rooms/<int:room_id>/switch-seat/", views.switch_seat_view),
    path("rooms/<int:room_id>/ready/", views.ready_view),
    path("rooms/<int:room_id>/move/", views.move_view),
    path("rooms/<int:room_id>/surrender/", views.surrender_view),
    path("rooms/<int:room_id>/chat/", views.chat_view),
    path("rooms/<int:room_id>/undo/request/", views.undo_request_view),
    path("rooms/<int:room_id>/undo/respond/", views.undo_response_view),
    path("rooms/<int:room_id>/seat-switch/respond/", views.seat_switch_response_view),
    path("solo/ai-move/", views.solo_ai_move),
]
